version: '3.8'
services:
  mysql:
    image: mysql:8.0.1
    container_name: mysqlDB
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - '3306'

  myapp:
    container_name: myapp
    image: demoshop
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql

volumes:
  mysql_db: